# Generated by Django 4.1.2 on 2022-11-23 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_course_title_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='product',
            new_name='course',
        ),
    ]
