# Generated by Django 4.1.2 on 2022-12-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_course_video_alter_course_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
