# Generated by Django 4.1.2 on 2022-12-06 15:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_telegram_setting_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='blog',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
