# Generated by Django 4.1.2 on 2022-12-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_setting_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='blog',
        ),
    ]
