# Generated by Django 4.1.2 on 2022-12-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contactformmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(choices=[('Okundu', 'Okundu'), ('Okunmadı', 'Okunmadı'), ('Çözüldü', 'Çözüldü')], default='New', max_length=10),
        ),
    ]
